


with RANKED_SAL_CUSTOMER AS (

SELECT CUSTOMER_ID,
NAME,
CITY,
EMAIL,
PHONE_NUMBER,
ACCOUNT_BALANCE,
UPDATE_TS,
DENSE_RANK() OVER (PARTITION BY CITY ORDER BY ACCOUNT_BALANCE DESC) AS RNK 
FROM CUSTOMER_CLEAN
)

SELECT CUSTOMER_ID ,NAME,CITY ,ACCOUNT_BALANCE , RNK FROM RANKED_SAL_CUSTOMER 
WHERE RNK = 1 AND NAME IS NOT NULL

